// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAaLLtLdIqQhXDf2Dsc6NJkX1rwIxAG-d4',
    appId: '1:185553844307:web:4f1e21102a1f484b79aea6',
    messagingSenderId: '185553844307',
    projectId: 'onsei-6d842',
    authDomain: 'onsei-6d842.firebaseapp.com',
    storageBucket: 'onsei-6d842.appspot.com',
    measurementId: 'G-TX564V0QLY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvAwjsOJA7kmW4Zbv7Fdjkwa4xX3Nftrw',
    appId: '1:185553844307:android:659998bc1808064479aea6',
    messagingSenderId: '185553844307',
    projectId: 'onsei-6d842',
    storageBucket: 'onsei-6d842.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXnaMu2rw5xirKLiXymSbSDgAfQufNlCo',
    appId: '1:185553844307:ios:a4608b4ed6df4f3579aea6',
    messagingSenderId: '185553844307',
    projectId: 'onsei-6d842',
    storageBucket: 'onsei-6d842.appspot.com',
    iosBundleId: 'com.example.onsei',
  );
}
